version: "3.4"

services:
  redis:
    image: redis:7
    environment:
#      - REDIS_URL=redis://redis:6379
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
  publisher:
    build:
      context: .
      dockerfile: ./Publisher.App/Dockerfile
  subscriber:
    build:
      context: .
      dockerfile: ./Subscriber.App/Dockerfile